'use client';
import Link from 'next/link'; import {usePathname} from 'next/navigation'; import * as I from 'lucide-react'; import {useDemo} from '@/lib/demo-store'; import type {LucideIcon} from 'lucide-react';
export const Icon=I;
const nav: [string,string,LucideIcon][]=[['/dashboard','Dashboard',I.Home],['/comites/ende-corporacion','Comités',I.Users],['/temas/DEC-2026-0042','Temas',I.FileText],['/reportes','Reportes',I.BarChart3],['/configuracion','Configuración',I.Settings]];
export function Shell({children}:{children:React.ReactNode}){const path=usePathname();const{reset}=useDemo();return <><header><Link href="/dashboard" className="brand"><img src="/ende-logo.png" alt="ENDE Corporación"/><span><strong>ENDE DECIDE DIGITAL</strong><small>Información para mejores decisiones</small></span></Link><nav>{nav.map(([href,label,X])=><Link className={path===href?'active':''} href={href} key={label}><X size={18}/>{label}</Link>)}</nav><div className="profile"><b>JP</b><span>Juan Pérez<small>Presidencia</small></span></div></header><main>{children}</main><footer>ENDE DECIDE DIGITAL <i/> Información para mejores decisiones <span>ENDE Corporación　|　v1.0 <button onClick={reset}>Restablecer demo</button></span></footer></>}
export function Card({title,children,className='' ,action}:{title?:React.ReactNode;children:React.ReactNode;className?:string;action?:React.ReactNode}){return <section className={'card '+className}>{title&&<div className="cardhead"><h3>{title}</h3>{action}</div>}{children}</section>}
export function Badge({children,kind='blue'}:{children:React.ReactNode;kind?:string}){return <span className={'badge '+kind}>{children}</span>}
export function PageTitle({title,subtitle,actions}:{title:string;subtitle?:string;actions?:React.ReactNode}){return <div className="title"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div><div className="title-actions"><span>Martes, 8 de septiembre de 2026</span>{actions}</div></div>}
export function Status({closed=false,risk=false}:{closed?:boolean;risk?:boolean}){return <Badge kind={closed?'green':risk?'amber':'blue'}>{closed?'Cumplido':risk?'En riesgo':'Listo para comité'}</Badge>}
